language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t travis-test-image -f Dockerfile.dev .

script:
  - docker run -e CI=true peterfarrar/docker-react npm run test